#!/bin/bash

# See "update_messages" script for workflow

. ./script_vars

# compile .mo files for each language
for lang in $languages; do
    outputdir="${localeout}/${lang}/LC_MESSAGES"
    inputdir="${localein}/${lang}/LC_MESSAGES"
    if [[ "$lang" != "en" ]]; then
        msgcmp "${inputdir}/${domain}.po" "${localein}/${domain}.pot"
    fi
    msgfmt "${inputdir}/${domain}.po" -o "${outputdir}/${domain}.mo"
done
