#!/bin/bash

# Workflow
#
#   These scripts require the msgmerge and msgfmt utilities.  On Debian systems
#   these are available in the gettext package.
#
#	1: Update languages in "script_vars" as needed
#   2. Use this script to update message files, adding language codes
#       to $languages below as needed.
#   3. Edit .po files in the $localedir hierarchy for each language as needed.
#   4. Compile the binary .mo files by running the "build_messages_mo" script

. ./script_vars

# extract message strings into template
pygettext3 -d calibre2jellyfin -o "${localedir}/calibre2jellyfin.pot" "bin/calibre2jellyfin.py"

# create/merge .po files for each language
for lang in $languages; do
    outputdir="${localedir}/${lang}/LC_MESSAGES"
    mkdir -p "$outputdir"
    if [[ ! -e "${outputdir}/${domain}.po" ]]; then
        cp "${localedir}/${domain}.pot" "${outputdir}/${domain}.po"
    fi
    msgmerge --update "${outputdir}/${domain}.po" "${localedir}/${domain}.pot"
done
